### ISSUE TITLE
Problem with simulator

### ISSUE THREAD

**Issue by AlexSchmitz222** [kristian/JDigitalSimulator#3]
Hi There, 

I have a Problem with the Simulator.

I’ve built a Digital Simulation, and it works perfectly.
But when I save it and Transfer it to another PC via USB-Stick,
Then it’s unloadble. Sometimes  appears a Message with says “There was an error while loading the worksheet…”

Here's the Link To the Files: https://drive.google.com/open?id=0B-6WzVaGPG1wbVZrUTFIRkQxVHM

**Comment by kristian** [comment]
Hello Alex, thanks for using JDigitalSimulator! I checked your simulation. Fortunately this is not a bug, your simulation is simply too large to fit into what's configured to be the default Java stack size. To overcome that, simply download / extract the [latest release](https://github.com/kristian/JDigitalSimulator/releases), open a command prompt (Win+R, cmd, Enter), navigate to the folder you extracted the JAR file, and start the JDigitalSimulator using the command "java -Xss4m -jar jds-2.0.2.jar". Hope this helps. In case you are using Windows, you can also use the latest version of the EXE launcher, which will start the JDigitalSimulator with that option already.

**Comment by AlexSchmitz222** [comment]
Hi, Can you tell me, where I Can Download the EXE  please

**Comment by kristian** [comment]
If you check the link in my previous comment, just download and extract the ZIP archive provided. In there you'll find the Windows executable.
