### ISSUE TITLE
won't build with launch4j-maven-plugin 1.7.15

### ISSUE THREAD

**Issue by baranator** [kristian/JDigitalSimulator#5]
hi!

I was just about to bump the archlinux aur-package to version 2.0.3. When i tried to build JDigitalSimulator, maven threw the following error:

`[ERROR] Failed to execute goal com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.7.15:launch4j (l4j-clui) on project jds: Execution l4j-clui of goal com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.7.15:launch4j failed: An API incompatibility was encountered while executing com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.7.15:launch4j: java.lang.ExceptionInInitializerError: null
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.7.15
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/eike/.m2/repository/com/akathist/maven/plugins/launch4j/launch4j-maven-plugin/1.7.15/launch4j-maven-plugin-1.7.15.jar
[ERROR] urls[1] = file:/home/eike/.m2/repository/net/sf/launch4j/launch4j/3.9/launch4j-3.9-core.jar
[ERROR] urls[2] = file:/home/eike/.m2/repository/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar
[ERROR] urls[3] = file:/home/eike/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
[ERROR] urls[4] = file:/home/eike/.m2/repository/foxtrot/foxtrot/2.0/foxtrot-2.0.jar
[ERROR] urls[5] = file:/home/eike/.m2/repository/com/jgoodies/jgoodies-common/1.7.0/jgoodies-common-1.7.0.jar
[ERROR] urls[6] = file:/home/eike/.m2/repository/com/jgoodies/forms/1.2.1/forms-1.2.1.jar
[ERROR] urls[7] = file:/home/eike/.m2/repository/com/jgoodies/looks/2.2.2/looks-2.2.2.jar
[ERROR] urls[8] = file:/home/eike/.m2/repository/com/thoughtworks/xstream/xstream/1.4.8/xstream-1.4.8.jar
[ERROR] urls[9] = file:/home/eike/.m2/repository/xmlpull/xmlpull/1.1.3.1/xmlpull-1.1.3.1.jar
[ERROR] urls[10] = file:/home/eike/.m2/repository/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar
[ERROR] urls[11] = file:/home/eike/.m2/repository/org/apache/ant/ant/1.8.2/ant-1.8.2.jar
[ERROR] urls[12] = file:/home/eike/.m2/repository/org/apache/ant/ant-launcher/1.8.2/ant-launcher-1.8.2.jar
[ERROR] urls[13] = file:/home/eike/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[14] = file:/home/eike/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[15] = file:/home/eike/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.0.M1/org.eclipse.sisu.inject-0.3.0.M1.jar
[ERROR] urls[16] = file:/home/eike/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[17] = file:/home/eike/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.jar
[ERROR] urls[18] = file:/home/eike/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
[ERROR] urls[19] = file:/home/eike/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
[ERROR] urls[20] = file:/home/eike/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @a98ce67
[ERROR] -> [Help 1]
`
Increasing the Version of launch4j-maven-plugin to at least 2.1.0 in pom.xml fixes the problem for me. I am not to experienced in mvn so I am not sure if simply increasing the version number upstream is the way to go for all plattforms or if should patch the pom.xml just for the AUR-build?

**Comment by kristian** [comment]
Hey @baranator, I don't know what is the connection between the AUR package in Arch and my JDigitalSimulator?

Generally I don't see any issues in bumping the launch4j-maven-plugin version generally. Please feel free to suggest a PR for it and I am happy to merge it, if it helps you! 👍

**Comment by kristian** [comment]
Fixed with #6. Thanks!
