### ISSUE TITLE
JDigitalSimulator package for x64 platform

### ISSUE THREAD

**Issue by AppWoman** [kristian/JDigitalSimulator#7]
Could you please make available a package that runs on x64 Platform? The prerequirement is Amazon Corretto V.8.402.08.1, but this only works with x86 and not with the x64 package. We manage a portfolio of apps for educational institutions and need to keep it on x64.

**Comment by kristian** [comment]
Hey @AppWoman, generally my JDigitialSimulator is a Java application all along, meaning there is no external dependency to any native OS binaries. Also in Java there is no differentiation between a x64 and x86 application. If you want to run the application on any platform, all that is required is any kind of Java Virtual Machine (JVM). Download the latest version from the releases section and run it as described in the readme using:

```bash
java -jar jds-2.5.2.jar
```

Hope this helps.
